% Example call for the full-video preprocessing function.
%
% process_video(...
%     'raw_videos/HQ/subject_001.avi', ...
%     'landmarks/HQ/subject_001.csv', ...
%     'processed/student/HQ/4_sec/subject_001', ...
%     'BP-rPPG', 'subject_001', 'subject_001', 'HQ', ...
%     120, 80, [20 20]);
%
% Replace paths and BP labels with the corresponding dataset values.
